config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'sushi', to: 'sushis#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sushi.rb
class Sushi < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sushis_controller.rb
class SushisController < ApplicationController
  before_action :set_sushi, only: [:show]

  def show;
  end

  private

  def set_sushi
    @sushi = Sushi.order("RANDOM()").first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sushis_helper.rb
module SushisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SushiApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sushis/show.html.erb
<div class = 'container'>
  <div class = 'child'>
    <% if @sushi.present? %>
      <h2><%= @sushi.name  %></h2>
        <%= image_tag "#{@sushi.sushi_image}", width: '200', height: '200' %>
      <div>
      <br>
        <%= @sushi.comment %>
      </div>
      <br><br>
      <div>
        <%= link_to "もっと食う！", sushi_path %>
      </div>
    <% else %>
      <h2>情報が見つかりません</h2>
    <% end %>
  </div>
</div>